language: go

go:
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go test -covermode count -v -coverprofile profile.cov .
  - go test -covermode count -v -coverprofile profile.errors.cov ./errors
  - go test -covermode count -v -coverprofile profile.path.cov ./path
  - $HOME/gopath/bin/gocov convert *.cov > gocov.out
  - $HOME/gopath/bin/goveralls -coverprofile gocov.out -repotoken $COVERALLS_TOKEN

notifications:
  email:
    recipients:
      - eric.elsken@gmail.com
    on_success: change
    on_failure: always

