language: go

go:
  - 1.7

notifications:
  email:
    recipients:
      - eric.elsken@gmail.com
    on_success: change
    on_failure: change

install:
  - ./bin/travis/install

script:
  - ./bin/travis/test_coverage

after_success:
  - ./bin/coveralls/push_coverage
