language: go

go:
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - $HOME/gopath/bin/goveralls -v -repotoken $COVERALLS_TOKEN

notifications:
  email:
    recipients:
      - eric.elsken@gmail.com
    on_success: change
    on_failure: always

